# Please read this configuration file thoroughly before hosting the site.

version: 3

methods:
  youtube:
    title: YouTube
    enabled: true

  ia_wayback:
    title: Wayback Machine
    enabled: true

  ia_details:
    title: Archive.org Details
    enabled: true

  ia_cdx:
    title: Archive.org CDX
    enabled: true

  ghostarchive:
    title: GhostArchive
    enabled: true

  hackint_ya:
    title: "#youtubearchive"
    enabled: false
    username:
    password:

  distributed_youtube_archive:
    title: Distributed YouTube Archive
    enabled: true

  hobune_stream:
    title: Hobune.stream
    enabled: true

  filmot:
    # This is not the RapidAPI endpoint.
    title: Filmot
    enabled: false
    api_key:

  # Playboard's ratelimits are currently 1 per day, which is ridiculous, hence why this is disabled by default.
  # If anyone is actually paying money for a Playboard account, I would accept a PR to add login support, but I can't test it myself.
  playboard_co:
    title: Playboard.co
    enabled: false
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.%s.0.0 Safari/537.36"

  removededm:
    title: RemovedEDM
    enabled: false
    # These are not account usernames. Use Special:BotPasswords.
    # Only basic rights are necessary.
    username: null
    password: null

  odysee:
    title: Odysee
    enabled: true

  altcensored:
    title: altCensored
    enabled: true

  preservetube:
    title: PreserveTube
    enabled: true

  nyaneonline:
    title: Nyane.online
    enabled: true

  letsplayindex:
    title: Letsplayindex.com
    enabled: true

# Global User-Agent
user_agent: "FindYoutubeVideo/1.0 operated by XYZ"

# Sets the experiment base URL. *If you want to disable experiments, set this to null.*
# Occasionally, there might be something I want to test; for example, looking for
# edge cases in an API endpoint.
# If experiments are on, the site will send the results of these experiments to my server.
# The following information will be included in the report:
# - video ID
# - any necessary additional information
# Your IP address WILL NOT be associated with the report.
# Current list of experiments is in EXPERIMENTS.txt.
experiment_base_url: "https://fyt-helper.thetechrobo.ca/experiment"
